cmake -S ./ -B ./build -DCMAKE_CXX_STANDARD=20 -G "Visual Studio 16 2019" -A "x64" `
-DOPENEXR_BUILD_TOOLS:BOOL="0" `
-DOPENEXR_CXX_STANDARD:STRING="20" `
-DOPENEXR_INSTALL_PKG_CONFIG:BOOL="0" `
-DIMATH_HALF_USE_LOOKUP_TABLE:BOOL="0" `
-DOPENEXR_DEFLATE_TAG:STRING="v1.18" `
-DOPENEXR_IMAGES_REPO:STRING="https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images" `
-DOPENEXR_STATIC_LIB_SUFFIX:STRING="_static" `
-DOPENEXR_FORCE_INTERNAL_IMATH:BOOL="1" `
-DOPENEXR_FORCE_INTERNAL_DEFLATE:BOOL="1" `
-DOPENEXR_DEFLATE_REPO:STRING="https://github.com/ebiggers/libdeflate.git" `
-DOPENEXR_IMAGES_TAG:STRING="v1.0" `
-DOPENEXR_BUILD_PYTHON:BOOL="1" `
-DCMAKE_CONFIGURATION_TYPES:STRING="Release" `
-DBUILD_TESTING:BOOL="0" `
-DCLANG_FORMAT_INCLUDES:STRING="*.h;*.cpp" `
-DCMAKE_INSTALL_PREFIX:PATH="P:/Code/OpenSource/openexr/build/__install" `
-DOPENEXR_INSTALL_EXAMPLES:BOOL="0" `
-DOPENEXR_INSTALL_TOOLS:BOOL="0" `
-DPYTHON_EXECUTABLE:STRING="C:/Users/Resartist/AppData/Local/Programs/Python/Python311/python.exe" `
-DPYBIND11_PYTHON_VERSION:STRING="3.11" `
-DIMATH_CXX_STANDARD:STRING="14" `
-DOPENEXR_INSTALL:BOOL="1" `
-DBUILD_SHARED_LIBS:BOOL="0"

cmake --build ./build --target PyOpenEXR --config Release
